version: '3'
services:
    e2e-qg:
        build:
            context: .
        env_file:
        - .env
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/code